# Generated by Django 5.1.7 on 2026-06-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='clinical_module_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, clinical features (event recording, vitals-based escalations, workflow checklists) are available to clinical staff. Operational features (bed management, admissions, dashboards) always work regardless of this flag.'),
        ),
    ]
